development:
    dialect: mysql
    dir: migrations
    # user_name:password@tcp(127.0.0.1)/dbname?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true
    datasource: isucari:isucari@tcp(127.0.0.1)/isucari?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true
