on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

name: CI

jobs: 
  back-lint:
    name: go-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.0
          working-directory: ./webapp/go/ # ここは適宜変える